apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      component: django
  template:
    metadata:
      labels:
        component: django
    spec:
      containers:
        - name: django
          image: scpomedialab/resin-annuaire-backend
          env:
            - name: RESIN_DOCKER_CONTAINER
              value: "django"
            - name: RESIN_DEBUG
              value: "false"
          imagePullPolicy: Always
          volumeMounts:
            - name: resin-database-vol
              mountPath: /app/data
            - name: resin-uploads-vol
              mountPath: /app/uploads
            - name: resin-staticfiles-vol
              mountPath: /app/static
      volumes:
        - name: resin-database-vol
          persistentVolumeClaim:
            claimName: resin-database-pvc
        - name: resin-uploads-vol
          persistentVolumeClaim:
            claimName: resin-uploads-pvc
        - name: resin-staticfiles-vol
          persistentVolumeClaim:
            claimName: resin-staticfiles-pvc
