services:
  frontend:
    # restart: "${RESTART_POLICY}"
    # image: scpomedialab/resin_frontend:${TAG}
    build: .
    ports:
      # - "${PUBLIC_PORT}:80"
      - 3001:80
    volumes:
      - uploads:/resin-backend/uploads
      - staticfiles:/resin-backend/static
    # env_file:
    #   - config-frontend.env

  django:
    build: ./backend
    # ports:
    #   - 8000:8000
    # image: scpomedialab/resin_api:${TAG}
    volumes:
      - database:/app/data # where the sqlite database will be stored (it should be backed up)
      - uploads:/app/uploads # user uploads, will be shared with the caddy server (it should be backed up)
      - staticfiles:/app/static # will be shared with the caddy server, rebuilt on every deployment

volumes:
  uploads:
  database:
  staticfiles:
