apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: scpomedialab/resin-annuaire
          imagePullPolicy: Always
