const remap = {
  Horodateur: "timestamp",
  Nom: "lastName",
  Prénom: "firstName",
  "Ville de l'institution": "city",
  "Adresse mail professionnelle": "email",
  "Téléphone professionnel": "phone",
  Fonction: "title",
  "Institution de rattachement": "organization",
  "Langues parlées": "languages",
  "Phrase courte de présentation": "shortBio",
  Biographie: "longBio",
  "Domaine d'expertise": "mainSkills",
  Compétences: "allSkills",
  "Lien vers page personnelle": "personalWebsite",
  "Lien vers page professionnelle": "professionalWebsite",
  Productions: "productions",
  Formations: "education",
  Activités: "activities",
  Responsabilités: "responsibilities",
  Distinctions: "distinctions",
  "Joindre une photo à votre profil": "avatar",
  Genre: "gender",
  "À afficher dans l'annuaire": "keep",
  "Ville de résidence": "city",
};

module.exports = remap;
