const remap = {
  Horodateur: "timestamp",
  Nom: "lastName",
  Prénom: "firstName",
  Ville: "city",
  "Adresse mail professionnelle": "email",
  "Téléphone professionnel": "phone",
  "Fonction/titre": "title",
  "Structure·s de rattachement": "organization",
  "Langues parlées": "languages",
  "Phrase courte de présentation": "shortBio",
  Biographie: "longBio",
  Compétences: "skills",
  "Lien vers page personnelle": "personalWebsite",
  "Lien vers page professionnelle": "professionalWebsite",
  Productions: "productions",
  Formations: "education",
  Activités: "activities",
  Responsabilités: "responsibilities",
  Distinctions: "distinctions",
  "Joindre une photo à votre profil": "avatar",
  "À afficher dans l'annuaire": "keep",
};

module.exports = remap;
