apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/deployment.yml
  - frontend/service.yml
  - django/deployment.yml
  - django/service.yml

commonLabels:
  owner: medialab
  name: resin-annuaire
