apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: resin.medialab.sciences-po.fr
      http:
        paths:
          - path: /
            backend:
              serviceName: frontend
              servicePort: 80
