apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: resin-sciencespo

bases:
  - ../../../base/

resources:
  - ingress.yml

patchesStrategicMerge:
  - env.yml

commonLabels:
  stage: prod

secretGenerator:
  - name: secrets
    env: secrets.env

images:
  - name: scpomedialab/resin-annuaire-backend
    newTag: "0.2.4"
  - name: scpomedialab/resin-annuaire
    newTag: "0.5.2"
